"""changed null constraint

Revision ID: 00e4efe10a62
Revises: 0cb3ddcfa30d
Create Date: 2022-01-13 15:38:29.292056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e4efe10a62'
down_revision = '0cb3ddcfa30d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'default_channel',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'default_channel',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
