"""added default_channel to servers

Revision ID: 0cb3ddcfa30d
Revises: 45a2156a9c92
Create Date: 2022-01-13 15:04:51.884865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb3ddcfa30d'
down_revision = '45a2156a9c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('default_channel', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'servers', 'channels', ['default_channel'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.drop_column('servers', 'default_channel')
    # ### end Alembic commands ###
